initialize-release
initializeCommons
  self at: #'Integer' put: Integer.
  self at: #'SmallInteger' put: SmallInteger.
  self at: #'LargeInteger' put: LargeInteger.
  self at: #'Float' put: Float.
  self at: #'ScaledDecimal' put: ScaledDecimal.
  self at: #'Object' put: Object.
  self at: #'Class' put: Class.
  self at: #'Behavior' put: Behavior.
  self at: #'Character' put: Character.
  self at: #'ByteArray' put: ByteArray.
  self at: #'Array' put: Array.
  self at: #'Boolean' put: Boolean.
  self at: #'Metaclass' put: Metaclass3.
  self at: #'Metaclass3' put: Metaclass3.
  self at: #'BlockClosure' put: BlockClosure.
  self at: #'UndefinedObject' put: UndefinedObject.
  self at: #'ByteString' put: String.
