#!/bin/bash
set -e
set -x

if [ "$#" -ne 1 ]; then
    echo "Usage createGsSqueakStone <stone name>"
    exit 1
fi

#createStone -f "testRun" 3.5.0
todeRestore "testRun" tode.dbf
startTopaz "testRun" -l << EOF
set u SystemUser p swordfish
login
run
SystemObjectSecurityPolicy worldAuthorization: #write.
(AllUsers userWithId: 'DataCurator') addPrivilege: #'CompilePrimitives'.
%
run
GsCompilerClasses keysAndValuesDo: [:symbol : class | Globals at: symbol put: class ]
%
commit
logout
login

input $GS_HOME/server/stones/testRun/product/upgrade/GsNMethodIr.gs

commit
logout
set u DataCurator p swordfish
login
method: Behavior
_clearSubclassesDisallowed
    self _unsafeAt: 2 put: (format bitAnd: (16r20 bitInvert))
%
send Behavior _clearSubclassesDisallowed
commit
logout
exit
EOF

todeIt testRun mc load BPBugFixes filetree://$GS_HOME/shared/repos/BP2017RH1/tools/bugfixes
todeIt testRun mc load MCEnvSwitch filetree://$GS_HOME/shared/repos/BP2017RH1/tools/MCEnvSwitch
todeIt testRun mc load SqueakParser filetree://$GS_HOME/shared/repos/BP2017RH1/parser
todeIt testRun mc load SqueakEnvironments filetree://$GS_HOME/shared/repos/BP2017RH1/tools/SqueakEnvironments

startTopaz "testRun" -l << EOF
login
run
MCEnv set: 7.
MCEnv useSqueakParser.
Environment initialize.
%
commit
logout
exit
EOF

todeIt -D testRun mc load SqNumbers filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt -D testRun mc load SqNumbers filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
startTopaz "testRun" -l << EOF
login
run
Magnitude _setSelfCanBeSpecial.
Number _setSelfCanBeSpecial.
%
commit
logout
exit
EOF

todeIt testRun mc load SqBooleans filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt testRun mc load SqClasses filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt testRun mc load SqKernel filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt testRun mc load SqUndefinedObject filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt testRun mc load SqCharacter filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport

startTopaz "testRun" -l << EOF
login
run
SmalltalkImage newMethodFromSqueakString: 'addToStartUpList: anObject' inEnv: 7
%
commit
logout
exit
EOF
todeIt -D testRun mc load SqCollectionLiterals filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport

