#!/bin/bash
set -e
set -x

restore=false
while getopts "r" opt; do
	case $opt in
		r) restore=true
		;;
	esac
done

shift $((OPTIND-1))
name=$1;


if $restore
then
	todeRestore $name tode.dbf
else
	createStone -f $name 3.5.0
fi

startTopaz $name -l << EOF
set u SystemUser p swordfish
login
run
SystemObjectSecurityPolicy worldAuthorization: #write.
(AllUsers userWithId: 'DataCurator') addPrivilege: #'CompilePrimitives'.
%
run
GsCompilerClasses keysAndValuesDo: [:symbol : class | Globals at: symbol put: class ]
%
commit
logout
login

input $GS_HOME/server/stones/$name/product/upgrade/GsNMethodIr.gs

commit
logout
set u DataCurator p swordfish
login
method: Behavior
_clearSubclassesDisallowed
    self _unsafeAt: 2 put: (format bitAnd: (16r20 bitInvert))
%
send Behavior _clearSubclassesDisallowed

env 7
method: Class
name
	^ self @env0: name
%

commit
logout
exit
EOF

todeIt $name mc load BPBugFixes filetree://$GS_HOME/shared/repos/BP2017RH1/tools/bugfixes
todeIt $name mc load MCEnvSwitch filetree://$GS_HOME/shared/repos/BP2017RH1/tools/MCEnvSwitch
todeIt $name mc load SqueakParser filetree://$GS_HOME/shared/repos/BP2017RH1/parser
todeIt $name mc load SqSuperclasses filetree://$GS_HOME/shared/repos/BP2017RH1/tools/superclasses
todeIt $name mc load SqueakEnvironments filetree://$GS_HOME/shared/repos/BP2017RH1/tools/SqueakEnvironments
todeIt $name mc load SqContext filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqClassCreation filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load Workspace filetree://$GS_HOME/shared/repos/BP2017RH1/tools
todeIt $name mc load BPGsTests filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport


startTopaz $name -l << EOF
login
run
MCEnv set: 7.
MCEnv useSqueakParser.
Environment initialize.
%
commit
logout
exit
EOF

todeIt $name mc load SqContext7 filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqBooleans filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqClasses filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
startTopaz $name -l << EOF
login
run
(SqueakEnvironment at: #ProtoObject) _setSelfCanBeSpecial.
%
commit
logout
exit
EOF

todeIt $name mc load SqNumbers filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
startTopaz $name -l << EOF
login
run
(SqueakEnvironment at: #Magnitude) _setSelfCanBeSpecial.
(SqueakEnvironment at: #Number) _setSelfCanBeSpecial.
(SqueakEnvironment at: #Integer) _setSelfCanBeSpecial.
(SqueakEnvironment at: #ScaledDecimal) _setSelfCanBeSpecial.
(SqueakEnvironment at: #Fraction) _setSelfCanBeSpecial.
%
commit
logout
exit
EOF

todeIt $name mc load SqKernel filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqCharacter filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport

startTopaz $name -l << EOF
login
run
SmalltalkImage newMethodFromSqueakString: 'addToStartUpList: anObject' inEnv: 7.
SmalltalkImage newMethodFromSqueakString: 'addToShutDownList: anObject' inEnv: 7.
SmalltalkImage newMethodFromSqueakString: 'removeFromStartUpList: anObject' inEnv: 7.
SmalltalkImage newMethodFromSqueakString: 'removeFromShutDownList: anObject' inEnv: 7.
UserGlobals at: #ByteString put: String.
UserGlobals at: #ByteSymbol put: Symbol.
UserGlobals at: #MethodDictionary put: Dictionary.
SqueakEnvironment recompileAllMethods.
%
commit
logout
exit
EOF
todeIt $name mc load SqCollectionLiterals filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqCollections filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SqExceptions filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport
todeIt $name mc load SUnit filetree://$GS_HOME/shared/repos/BP2017RH1/SqueakImport

