#!/bin/bash
while IFS= read line; do
    echo "$line"
    echo "$line" | grep -E "errors while loading|Press 'Proceed' to continue\." && echo "found error" && spd-say 'I am afraid I cannot do that, Dave.' && exit 7;
done
exit 0;
