SystemOrganization addCategory: #'GemStoneGUI-Tools'!
SystemOrganization addCategory: #'GemStoneGUI-TopazInterface'!
SystemOrganization addCategory: #'GemStoneGUI-Repositories'!
SystemOrganization addCategory: #'GemStoneGUI-Serialization'!
SystemOrganization addCategory: #'GemStoneGUI-Squeak'!
SystemOrganization addCategory: #'GemStoneGUI-GemStone'!
SystemOrganization addCategory: #'GemStoneGUI-Proxies'!
