'From Squeak6.0alpha of 20 March 2017 [latest update: #17058] on 14 March 2018 at 4:25:26 pm'!
Smalltalk at: #TextConstants put: SymbolDictionary new!
TextConstants at: #'BS' put:  (Character backspace)!
TextConstants at: #'BS2' put:  ($ž)!
TextConstants at: #'Basal' put:  0!
TextConstants at: #'Bold' put:  1!
TextConstants at: #'CR' put:  (Character cr)!

TextConstants at: #'Centered' put:  2!
TextConstants at: #'Clear' put:  ($­)!
TextConstants at: #'CrLf' put:  ('

')!
TextConstants at: #'CrLfCrLf' put:  ('



')!
TextConstants at: #'CrossedX' put:  258!
TextConstants at: #'CtlW' put:  ($‘)!
TextConstants at: #'CtrlA' put:  ($Ô)!
TextConstants at: #'CtrlB' put:  ($æ)!
TextConstants at: #'CtrlC' put:  ($ä)!
TextConstants at: #'CtrlD' put:  ($Ä)!
TextConstants at: #'CtrlDigits' put:  (#(159 144 143 128 127 129 131 180 149 135))!
TextConstants at: #'CtrlE' put:  ($Â)!
TextConstants at: #'CtrlF' put:  ($â)!
TextConstants at: #'CtrlG' put:  ($ñ)!
TextConstants at: #'CtrlH' put:  ($ó)!
TextConstants at: #'CtrlI' put:  ($Ö)!
TextConstants at: #'CtrlJ' put:  ($å)!
TextConstants at: #'CtrlK' put:  ($È)!
TextConstants at: #'CtrlL' put:  ($Ù)!
TextConstants at: #'CtrlM' put:  ($ö)!
TextConstants at: #'CtrlN' put:  ($õ)!
TextConstants at: #'CtrlO' put:  ($Ø)!
TextConstants at: #'CtrlOpenBrackets' put:  (#(201 7 218 249 219 15))!
TextConstants at: #'CtrlP' put:  ($Ê)!
TextConstants at: #'CtrlQ' put:  ($Ò)!
TextConstants at: #'CtrlR' put:  ($ï)!
TextConstants at: #'CtrlS' put:  ($Ó)!
TextConstants at: #'CtrlT' put:  ($ð)!
TextConstants at: #'CtrlU' put:  ($Å)!
TextConstants at: #'CtrlV' put:  ($Æ)!
TextConstants at: #'CtrlW' put:  ($Ñ)!
TextConstants at: #'CtrlX' put:  ($×)!
TextConstants at: #'CtrlY' put:  ($ò)!
TextConstants at: #'CtrlZ' put:  ($ç)!
TextConstants at: #'Ctrla' put:  (Character value: 1)!
TextConstants at: #'Ctrlb' put:  ($¦)!
TextConstants at: #'Ctrlc' put:  ($ä)!
TextConstants at: #'Ctrld' put:  ($„)!
TextConstants at: #'Ctrle' put:  ($‚)!
TextConstants at: #'Ctrlf' put:  (Character newPage)!
TextConstants at: #'Ctrlg' put:  ($è)!
TextConstants at: #'Ctrlh' put:  ($³)!
TextConstants at: #'Ctrli' put:  ($–)!
TextConstants at: #'Ctrlj' put:  ($¥)!
TextConstants at: #'Ctrlk' put:  ($ˆ)!
TextConstants at: #'Ctrll' put:  ($™)!
TextConstants at: #'Ctrlm' put:  ($¶)!
TextConstants at: #'Ctrln' put:  (Character value: 14)!
TextConstants at: #'Ctrlo' put:  (Character value: 15)!
TextConstants at: #'Ctrlp' put:  ($Š)!
TextConstants at: #'Ctrlq' put:  (Character value: 17)!
TextConstants at: #'Ctrlr' put:  (Character value: 18)!
TextConstants at: #'Ctrls' put:  (Character value: 19)!
TextConstants at: #'Ctrlt' put:  (Character value: 11)!
TextConstants at: #'Ctrlu' put:  (Character value: 21)!
TextConstants at: #'Ctrlv' put:  ($†)!
TextConstants at: #'Ctrlw' put:  ($‘)!
TextConstants at: #'Ctrlx' put:  ($—)!
TextConstants at: #'Ctrly' put:  ($²)!
TextConstants at: #'Ctrlz' put:  ($§)!
TextConstants at: #'DefaultBaseline' put:  12!
TextConstants at: #'DefaultEditMenuMessages' put:  (#(#again #copySelection #cut #paste #undo #save #cancel #align #fit))!
TextConstants at: #'DefaultFontFamilySize' put:  3!
TextConstants at: #'DefaultLineGrid' put:  16!
TextConstants at: #'DefaultMarginTabsArray' put:  (#(#(24 24) #(48 48) #(72 72) #(96 96) #(120 120) #(144 144) #(168 168) #(192 192) #(216 216) #(240 240) #(264 264) #(288 288) #(312 312) #(336 336) #(360 360)))!
TextConstants at: #'DefaultMask' put:  (Color black)!
TextConstants at: #'DefaultMultiStyle' put:  TextStyle default!
TextConstants at: #'DefaultRule' put:  3!
TextConstants at: #'DefaultSpace' put:  4!
TextConstants at: #'DefaultTab' put:  24!
TextConstants at: #'DefaultTabsArray' put:  (#(24 48 72 96 120 144 168 192 216 240 264 288 312 336 360 384 408 432 456 480 504 528 552 576 600 624 648 672 696 720))!
TextConstants at: #'ESC' put:  ($ )!
TextConstants at: #'EndOfRun' put:  257!
TextConstants at: #'Enter' put:  (Character value: 3)!
TextConstants at: #'Italic' put:  2!
TextConstants at: #'Justified' put:  3!
TextConstants at: #'LeftFlush' put:  0!
TextConstants at: #'LeftMarginTab' put:  1!
TextConstants at: #'RightFlush' put:  1!
TextConstants at: #'RightMarginTab' put:  2!
TextConstants at: #'Space' put:  (Character space)!
