*Morphic-MorphicExtras-parts bin
supplementaryPartsDescriptions
	"Extra items for parts bins"

	^ {DescriptionForPartsBin
		formalName: 'Column' translatedNoop
		categoryList: #()
		documentation: 'An object that presents the things within it in a column' translatedNoop
		globalReceiverSymbol: #AlignmentMorph
		nativitySelector: #columnPrototype.
	DescriptionForPartsBin
		formalName: 'Row' translatedNoop
		categoryList: #()
		documentation: 'An object that presents the things within it in a row' translatedNoop
		globalReceiverSymbol: #AlignmentMorph
		nativitySelector: #rowPrototype}