instance creation
addDullerWindowColors: theme

	theme
		set: #uniformWindowColor for: #Model to: Color veryVeryLightGray duller;
		set: #customWindowColor for: #Browser to: (Color r: 0.764 g: 0.9 b: 0.63) duller;
		set: #customWindowColor for: #ChangeList to: (Color r: 0.719 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #ChangeSorter to: (Color r: 0.719 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #ChatNotes to: (Color r: 1.0 g: 0.7 b: 0.8) duller;
		set: #customWindowColor for: #ClassCommentVersionsBrowser to: (Color r: 0.753 g: 0.677 b: 0.9) duller;
		set: #customWindowColor for: #Debugger to: (Color r: 0.9 g: 0.719 b: 0.719) duller;
		set: #customWindowColor for: #DualChangeSorter to: (Color r: 0.719 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #FileContentsBrowser to: (Color r: 0.7 g: 0.7 b: 0.508) duller;
		set: #customWindowColor for: #FileList to: (Color r: 0.65 g: 0.65 b: 0.65) duller;
		set: #customWindowColor for: #InstanceBrowser to: (Color r: 0.726 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #Lexicon to: (Color r: 0.79 g: 0.9 b: 0.79) duller;
		set: #customWindowColor for: #MCTool to: (Color r: 0.65 g: 0.691 b: 0.876) duller;
		set: #customWindowColor for: #MessageNames to: (Color r: 0.639 g: 0.9 b: 0.497) duller;
		set: #customWindowColor for: #MessageSet to: (Color r: 0.719 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #PackagePaneBrowser to: (Color r: 0.9 g: 0.9 b: 0.63) duller;
		set: #customWindowColor for: #PluggableFileList to: Color lightYellow duller;
		set: #customWindowColor for: #PreferenceBrowser to: (Color r: 0.671 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #SMLoader to: (Color r: 0.801 g: 0.801 b: 0.614) duller;
		set: #customWindowColor for: #SMLoaderPlus to: (Color r: 0.801 g: 0.801 b: 0.614) duller;
		set: #customWindowColor for: #SMReleaseBrowser to: (Color r: 0.801 g: 0.801 b: 0.614) duller;
		set: #customWindowColor for: #ScriptingDomain to: (Color r: 0.91 g: 0.91 b: 0.91) duller;
		set: #customWindowColor for: #SelectorBrowser to: (Color r: 0.45 g: 0.9 b: 0.9) duller;
		set: #customWindowColor for: #StringHolder to: (Color r: 0.9 g: 0.9 b: 0.719) duller;
		set: #customWindowColor for: #TestRunner to: (Color r: 0.9 g: 0.576 b: 0.09) duller;
		set: #customWindowColor for: #TranscriptStream to: (Color r: 0.9 g: 0.75 b: 0.45) duller;
		set: #customWindowColor for: #VersionsBrowser to: (Color r: 0.782 g: 0.677 b: 0.9) duller.