SystemOrganization addCategory: #'GemStoneGUI-Tools'!
SystemOrganization addCategory: #'GemStoneGUI-Serialization'!
SystemOrganization addCategory: #'GemStoneGUI-Squeak'!
SystemOrganization addCategory: #'GemStoneGUI-GemStone-Core'!
SystemOrganization addCategory: #'GemStoneGUI-GemStone-Proxies'!
SystemOrganization addCategory: #'GemStoneGUI-Interfaces'!
SystemOrganization addCategory: #'GemStoneGUI-Transfer'!
